### PR TITLE
Add Elasticsearch check

### PR DESCRIPTION
**Pull request by kevintraver**

### CODE REVIEW

**Comment by ianheggie** [comment]
Checking if I can quickly fix the failing tests using branch kevintraver-elasticsearch

**Comment by ianheggie** [comment]
Unfortunately I wasn't able to quickly fix your branch by merging it into a fresh copy of master - I will leave it in your hands to get the tests passing.

**Comment by ianheggie** [comment]
Retesting against latest master

**Comment by zedtux** [comment]
@kevintraver can you please update your code so that we can get this merged in master? :)

**Comment by kevintraver** [comment]
I just rebased against master, and its still failing. I can't quite figure out why.

Seems like the `elasticsearch` gem is not getting added.

Could it be sometihng wrong with this line?

`gem 'elasticsearch', :require => !ENV['ELASTICSEARCH_URL'].nil?`

**Comment by zedtux** [comment]
As far as I can see, you could be on the right path. I found this in the build logs:

```
body: health_check failed: [elasticsearch - Wrong configuration. Missing 'elasticsearch' gem]
```

**Comment by ianheggie** [comment]
How are you going with this? I have also been flat chat and haven’t had the time to investigate.

**Comment by ianheggie** [comment]
Are you still intending to work on this? I don't have the time to attend to it presently (unfortunately).

**Pull request merged**
