### PR TITLE
Making middleware pattern matching different health checks URIs

### PR DESCRIPTION
**Pull request by filiphaftek**
With pattern containing middleware in our company we have problem that your defined health check '/health' is not matched. This small change in pattern should make all of the URIs work.

### CODE REVIEW

**Comment by ianheggie** [comment]
What is the problem you are attempting to fix with this pull request? (I don't understand the necessity of this change - please show a worked example, preferably as a test that fails with my existing code, but works with your changes).

**Comment by filiphaftek** [comment]
@ianheggie with this new pattern you've introduced 'middleware' word in URI which is mandatory. IMHO this is not the best idea as you expose the underneath implementation in URI (if I use controller or middleware it should be transparent). With this 'middleware' word, existing checks in our company stopped to work as we have just simple '/health' URI - no 'middleware' word inside it. I've liked that you changed this pattern to be very precise and with the small update I propose this should work also for existing  checks. I've tried to fix the tests.

**Comment by ianheggie** [comment]
The alternative is to have middleware as a different uri, which would be cleaner. There definitely needs to be some differentiator as using middleware disables the full stack test. I would be happy with a config.url (default 'health_check' and config.middleware_uri (default 'health_check_middleware') and you reconfigure the middleware uri as appropriate.

**Comment by lowang** [comment]
@ianheggie may I suggest another approach: https://github.com/ianheggie/health_check/pull/52/
It catches exceptions that @filiphaftek wanted but is using full rails stack to perform all checks.
Thus no need to separate endpoint is needed.

**Comment by ianheggie** [comment]
lowang - your suggestion ( #52 ) has merit for other reasons, but conflicts with the original intent of adding middleware (to allow a success response when the later part of the stack is not working (eg because of DB connection issue)).

**Comment by ianheggie** [comment]
I am going a slightly different direction - which I believe will satisfy what filiphaftek wants - extract from README:

=== Installing As Middleware

Install health_check as middleware if you want to sometimes ignore exceptions from later parts of the Rails middleware stack,
eg DB connection errors from QueryCache. The "middleware" check will fail if you have not installed health_check as middleware.

To install health_check as middleware add the following line to the config/application.rb:
    config.middleware.insert_after "Rails::Rack::Logger", HealthCheck::MiddlewareHealthcheck

Note: health_check is installed as a full rails engine even if it has been installed as middleware. This is so the
remaining checks continue to run through the complete rails stack.

You can also adjust what checks are run from middleware, eg if you want to exclude the checking of the database etc, then set
  config.middleware_checks = ['middleware', 'standard', 'custom']
  config.standard_checks = ['middleware', 'custom']

Middleware checks are run first, and then full stack checks.

**Comment by ianheggie** [comment]
I have implemented a slightly different approach - adjust the list of checks to be done in middleware (eg in your case, add 'standard') and adjust the standard check to make sure you only run the checks you want to from middleware. Thanks for the input (The delay was in updating the tests and making middleware handle the enhancements already in the full stack test).

**Pull request closed without merging**
