### PR TITLE
Merge PR #29 into pre_rails4

### PR DESCRIPTION
**Pull request by kevintraver**
This merges from PR #29 add predefined checks for s3 buckets permissions, Redis, Sidekiq and Rescue, and Elasticsearch connectivity

### CODE REVIEW

**Comment by kevintraver** [comment]
Ah, Looks like there needs to be an update for the travis environment.

**Comment by ianheggie** [comment]
Having a quick glance to see if I can fix failing tests using branch kevintraver-pre_rails

**Comment by ianheggie** [comment]
Merging the current pre_rails4 in should help with getting the test working.

**Comment by ianheggie** [comment]
Retesting against latest pre_rails4 in kevintraver-pre_rails4 branch

**Comment by kevintraver** [comment]
Thanks for looking into this. Let me know if theres anything I can do to help

**Comment by ianheggie** [comment]
I haven’t had the time to look at this - are you able to resolve the conflicts please?

**Comment by kevintraver** [comment]
I cant seem to repeat the problem. I will rebase against master and try again.

**Comment by ianheggie** [comment]
Are you still intending to rebase and try again? I don't have the time to attend to it presently (unfortunately).

**Pull request closed without merging**
