### PR TITLE
Use before_action instead of before_filter

### LINKED ISSUE #44: Deprecation warning with Rails 5
**DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead.**

After constantly seeing that warning for days, I finally tracked it down to this gem. I forked it and changed the one place I saw it. Warning have since cleared.

The modification made was in `lib\health_check\health_check_controller.rb` 
from:
```ruby
module HealthCheck
  class HealthCheckController < ActionController::Base

    layout false if self.respond_to? :layout
    before_filter :authenticate
```
to:
```ruby
module HealthCheck
  class HealthCheckController < ActionController::Base

    layout false if self.respond_to? :layout
    before_action :authenticate
```

### PR DESCRIPTION
**Pull request by lime**
Fixes #44

### CODE REVIEW

**Comment by ianheggie** [comment]
Unfortunately it doesn't pass all the tests - please fix so the PR can be merged. (Probably best to rebase on latest master or merge latest master)

**Comment by corrupt952** [comment]
Duplicate of #39.

**Comment by lime** [comment]
This is already based on the current master (414689d). The build error seems to be unrelated to this change.

If I read the issue linked to from the duplicate PR correctly (https://github.com/bundler/bundler/issues/4975), this error will be fixed by Bundler 1.13.2, which is yet to be released.

**Comment by ianheggie** [comment]
Looks like yujideveloper is all over it in #39 - he is working on a fix for the bundler/jruby conflict (Thanks @corrupt952 for the pointer )

**Comment by lime** [comment]
👍  Good to know, no need to duplicate all the effort. :)

I already took a stab at getting the tests to pass in a separate branch, will open a PR if it worked. If not, it looks like @yujideveloper has it covered.

**Pull request merged**
