### PR TITLE
feature: Implement IP whitelist

### PR DESCRIPTION
**Pull request by arbesulo**
Simple IP-Whitelisting feature

### CODE REVIEW

**Comment by arbesulo** [comment]
@ianheggie could you please give some feedback about this pull request?

**Comment by arbesulo** [comment]
@ianheggie are you there?

**Comment by ianheggie** [comment]
I am looking at your PR - I will adjust the default error return to 403 as that is more appropriate.

**Comment by arbesulo** [comment]
Sure, thanks :)

**Pull request merged**
