### PR TITLE
Health check as middleware

### PR DESCRIPTION
**Pull request by filiphaftek**
Add health check as middleware so even if database in not working health checks is responding properly. With health check as controller approach, because of ActiveRecord cache middleware, in case of error connecting database application is returning http 500 with html. This PR adds new way of adding health check to application.

### CODE REVIEW

**Comment by ianheggie** [comment]
Please merge latest master and fix any remaining test failures - then I can merge this in. I like how clean you made it to add it as middleware. What happens to the auto routing if you add it as middleware under a non standard url?

**Comment by filiphaftek** [comment]
Latest master was merged already. Both failing test seems to be unrelated to this change IMHO (but I could be wrong of course :) If you add middleware not under `health_check` url, you will have  two separate health check urls (one from middleware and one from application controller - just tested it).

**Comment by ianheggie** [comment]
One of the other contributors is working on a fix to the broken test (A bundler / jruby conflict) in #39 - when he is done and I have merged his fix, you can merge in master and fix your tests.

**Comment by filiphaftek** [comment]
@ianheggie all tests are passing, when can we expect this feature to be merged? I'm asking as my company wants to switch from our fork to your public gem.

**Comment by ianheggie** [comment]
Just a heads up that your middleware contribution will be changed in the next release to conform to the standard url convention, and it will be only used where "middleware" is included in the list of checks (eg /health_check/middleware_s3 rather than /arbitrary-text/healthcheck?checks=s3. This comes out of adding tests to confirm behaviour. I will bump the minor version # at the time.

**Pull request merged**
